### ISSUE TITLE
Vue Look / désactiver le look visualisé

### ISSUE THREAD

**Issue by FlorineBcs** [remia/EclairLooks#1]
Dans la vue look, on choisit dans la colonne du centre un look qui est visualisé en bas. Peut-on désactiver le choix pour voir l'identité? (par défaut un look est nécessairement selectionné)
intéret : pour des looks scene referred, on peut voir seulement le tone mapping ou look + tone mapping.

**Comment by remia** [comment]
C'est maintenant possible dans la version 0.2.5
